name: Terraform CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform validate & lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive -diff

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive
